### ISSUE TITLE
Basic UI: Edit page + View as markdown

### ISSUE THREAD

**Issue by elimisteve** [cryptag/notes#1]
Basically copying GitHub, but forgetting the bold/italics/underline/etc buttons for now: https://tryingtobeawesome.com/files/screenshot-github-cryptag-notes-mock.png

**Comment by jimmcgaw** [comment]
Is part of this to have both a "Write" and "Preview" tab in edit mode? Do we want a WYSIWYG style editor for markdown?

**Comment by elimisteve** [comment]
@jimmcgaw I say WYSIWYG is unnecessary for now, but I really like the Preview tab you started on earlier.

**Comment by jimmcgaw** [comment]
I think 98e4dea7057eb31bfd3ae69477dc2d2ca23416a3 and cde37b1c807e6680c50cf03e79757292b8a1b64b address much of this.

**Comment by elimisteve** [comment]
Done a couple weeks ago.

_Great_ work, @jimmcgaw!
