### ISSUE TITLE
Backends: Add ability to create new ones from UI

### ISSUE THREAD

**Issue by elimisteve** [cryptag/notes#20]
- [ ] Filesystem
- [ ] Webserver
- [ ] Sandstorm

Let's nail ^^those 3^^ first and worry about `DropboxRemote` later.

**Comment by jimmcgaw** [comment]
I think we might get to a point where we want some basic routing in place? We seem to watch some of the CRUD views for backends and pages. We might want an "account settings" page eventually, and there's a request for a "Feedback" page.

**Comment by elimisteve** [comment]
Hmm good point; adding routing sounds like a good idea.

**Comment by elimisteve** [comment]
User explicitly asked to do this
