### ISSUE TITLE
Convert Layout to Flexbox

### ISSUE THREAD

**Issue by jimmcgaw** [cryptag/notes#25]
There are bugs with the current layout. Rather than hack around, learn the basics of a flexbox layout and convert the site to use this in the styles instead of hackily floated divs.

**Comment by elimisteve** [comment]
@jimmcgaw I've been told that http://flexboxfroggy.com/ is great but I haven't gone through it yet.

**Comment by elimisteve** [comment]
I quickly learned some flexbox a few months ago via https://css-tricks.com/snippets/css/a-guide-to-flexbox/ and https://scotch.io/tutorials/a-visual-guide-to-css3-flexbox-properties , but forgot almost all of it :-(. (Use it or lose it, I suppose.)

**Comment by elimisteve** [comment]
@jimmcgaw Think this is enough flexbox-ification?

**Comment by elimisteve** [comment]
Calling this Good Enough, at least for now
