### ISSUE TITLE
UI bug: white background should extend to bottom of window, not just bottom of viewport

### ISSUE THREAD

**Issue by elimisteve** [cryptag/notes#26]
@jimmcgaw More easily fixable once #25 is in place, perhaps?

Screenshot:
![screenshot-cryptag-notes-bug-whitebackgroundstopsatinitialbottomofscreen-shouldcontinuewithscroll-screenshot - 12142016 - 11 49 40 pm](https://cloud.githubusercontent.com/assets/139603/21215803/40d16f9e-c258-11e6-8c66-c968b3337c4f.png)

**Comment by jimmcgaw** [comment]
This is why #25 :)

**Comment by elimisteve** [comment]
@jimmcgaw Right now my core goal is to release a polished version of Notes ASAP (as per https://github.com/cryptag/notes/milestone/2 ).  Think going flexbox is the best way forward?  If so I'm going to try implementing it today/tomorrow.

Thanks!

**Comment by jimmcgaw** [comment]
Sweet! My vote's for flexbox but I would use whatever you can to make things happen quickly. As I don't need to tell you, there's a number of grid layout libraries available, like Bourbon neat, some flexbox-specific ones, and there's one included in Bootstrap. I might not be able to help out until later this week or the weekend, but keep me appraised, I do want to help you hit this milestone.

**Comment by elimisteve** [comment]
Depending on what our end solution looks like, https://github.com/andreypopp/react-textarea-autosize may help here.
