### ISSUE TITLE
UI Tweak: Increase default font size

### ISSUE THREAD

**Issue by elimisteve** [cryptag/notes#28]
@jimmcgaw What do you think of making this configurable? My browser's default font size is very large compared to most people's, and this helps save my eyes by reducing eye strain.

**Comment by jimmcgaw** [comment]
I'm not opposed to this, but I'd say it's early to introduce a user-configurable variable, both in terms of the app's maturity with its users and the app's code itself. (We don't have any routing, this is just a SPA, and I don't think there's a strong enough use case for visually cluttering up the sidebar with this.)

I would like to make it bigger tho, at least 14px. What part of the UI are you referring to? All of it? Just the doc section?

**Comment by elimisteve** [comment]
Just increasing the default but not making it user-editable for now sounds great :+1:.

To me the parts that it'd be nice to make bigger are:

- [ ] Page titles along the left (a bit bigger; the contrast is awesomely high (white on dark, funky purple) so this isn't bad IMO)
- [ ] Size of document text
- [ ] Size of the username in the top-left

@jimmcgaw What do you think?
