### ISSUE TITLE
Usability: On startup: Prompt user for username

### ISSUE THREAD

**Issue by elimisteve** [cryptag/notes#35]
...but unrelated errors may have prevented this from happening; I think this functionality is already there...

**Comment by jimmcgaw** [comment]
What is the bug here? Is the prompt not happening when you think it's supposed to? What conditions lead to what behavior?

**Comment by elimisteve** [comment]
Status: asking user for more info. This was probably in the context of `cryptagd` not being found.

**Comment by Daem0nX** [comment]
I did receive a username prompt after the first launch. I recall a username setting sometime in a past test for cryptag, but I left it as the developers name. Should that have carried over, or what was the expected behavior?

**Comment by elimisteve** [comment]
If you received a prompt and it persisted, then this is all good.

Username was hard coded in `app/App.js`, which is probably what you're thinking of, but now it's all in the GUI :-).
