### ISSUE TITLE
On startup: Remember previously-chosen Backend

### ISSUE THREAD

**Issue by elimisteve** [cryptag/notes#9]

**Comment by elimisteve** [comment]
@jimmcgaw localStorage, perhaps? Could have a config file sitting some place that it reads off disk... but actually, it'd be sweet to remove Electron's permissions to touch disk, in which case localStorage sounds even better.

**Comment by jimmcgaw** [comment]
Fixed in cd9f9ea382e39242d9e054c28de82a8ad921ff7f
